// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6XPW7t5qiFnTDo9dRGBVXRSommtFgAs',
    appId: '1:582652587994:web:bb603283ef5c916b8fdae3',
    messagingSenderId: '582652587994',
    projectId: 'nxlapp-7fb70',
    authDomain: 'nxlapp-7fb70.firebaseapp.com',
    storageBucket: 'nxlapp-7fb70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPvcP7eWjF-zgAbN3qOiESkNwNYNrwgo',
    appId: '1:582652587994:android:69e6f1bc6d8dab9d8fdae3',
    messagingSenderId: '582652587994',
    projectId: 'nxlapp-7fb70',
    storageBucket: 'nxlapp-7fb70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAX0g54zG2S-rX2TJDGhf9PRP_nXE8F1g',
    appId: '1:582652587994:ios:083051ab3b8446aa8fdae3',
    messagingSenderId: '582652587994',
    projectId: 'nxlapp-7fb70',
    storageBucket: 'nxlapp-7fb70.firebasestorage.app',
    iosBundleId: 'com.example.nxlapp',
  );
}
